### ISSUE TITLE
Does not work with Codeception 2.2 or 2.3.

### ISSUE THREAD

**Issue by discoinfiltrator** [grantlucas/phantoman#58]
In Phantoman.php, you have the line:

```
class Phantoman extends \Codeception\Platform\Extension
```

As of Codeception 2.2, this should be:

```
class Phantoman extends \Codeception\Extension
```

Currently we need to run a post install/update task to automate this, which isn't ideal.

**Comment by grantlucas** [comment]
Thanks for the heads up! I'll look into this shortly and get a new version tagged with changes.

**Comment by JorisVanEijden** [comment]
This is not an issue for me with Codeception 2.3.4 and Phantoman 1.1.7
Codeception uses a shim.php which aliases `\Codeception\Platform\Extension` to `\Codeception\Extension`.

What _is_ an issue is the use of the `module.init` event.

Since Codeception 2.2.7 it's possible to enable extensions per suite. But these are loaded by `registerSuiteExtensions` which is triggered by `module.init` so Phantoman is too late to register for that event.
Using `\Codeception\Events::SUITE_INIT` works fine.

**Comment by grantlucas** [comment]
I haven't had a chance to dig into this yet as I'm not using it day to day anymore. Would anyone be open to submitting a PR with some proposed changes?

**Comment by JorisVanEijden** [comment]
#59

**Comment by grantlucas** [comment]
@ksiv @discoinfiltrator When you have a moment, would you be able to give #59 a try with your projects and confirm if it addresses the issue you're seeing?

**Comment by grantlucas** [comment]
v2.0.0 has be tagged as a new release. Please update and let me know how things go with regards to this issue.

**Comment by ksiv** [comment]
Our project currently at 2.2.7 I ll be able to test it against this version of Codeception

**Comment by grantlucas** [comment]
Closing this issue as this project is working well with Codecpetion 2.5.x at this point
